version: "2.13"

services:
    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=node_chapter_2
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        ports:
           - 3333:3333
           - 9229:9229
        volumes:
            - .:/usr/app
        links:
            - database_ignite
        depends_on: 
            - database_ignite

volumes:
    pgdata: 
        driver: local